# Uncomment this line to define a global platform for your project
 platform :ios, '8.2'

target 'scan4pase' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for scan4pase
  pod 'MagicalRecord'
  pod 'Firebase'
  pod 'Firebase/Storage'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Messaging'
  pod 'StaticDataTableViewController'
  pod 'MTBBarcodeScanner'
end
